### ISSUE TITLE
Zenoh-python build failed with "error[E0164]: expected tuple struct or tuple variant..."

### ISSUE THREAD

**Issue by eddie9712** [eclipse-zenoh/zenoh-python#39]
Hi all , 
I am new to Rust and Zenoh,  When I was building the python client library, I got the errors below:
```
error[E0164]: expected tuple struct or tuple variant, found associated function `nix::Error::Sys`
  --> /home/eddie/.cargo/registry/src/github.com-1ecc6299db9ec823/shared_memory-0.11.4/src/unix.rs:87:13
   |
87 |         Err(nix::Error::Sys(Errno::EEXIST)) => return Err(ShmemError::MappingIdExists),
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `fn` calls are not allowed in patterns
   |
   = help: for more information, visit https://doc.rust-lang.org/book/ch18-00-patterns.html


error[E0164]: expected tuple struct or tuple variant, found associated function `nix::Error::Sys`
  --> /home/eddie/.cargo/registry/src/github.com-1ecc6299db9ec823/shared_memory-0.11.4/src/unix.rs:88:13
   |
88 |         Err(nix::Error::Sys(e)) => return Err(ShmemError::MapCreateFailed(e as u32)),
   |             ^^^^^^^^^^^^^^^^^^ `fn` calls are not allowed in patterns
   |
   = help: for more information, visit https://doc.rust-lang.org/book/ch18-00-patterns.html


    Buildingerror[E0164]: expected tuple struct or tuple variant, found associated function `nix::Error::Sys`
   --> /home/eddie/.cargo/registry/src/github.com-1ecc6299db9ec823/shared_memory-0.11.4/src/unix.rs:103:13
    |
103 |         Err(nix::Error::Sys(e)) => return Err(ShmemError::UnknownOsError(e as u32)),
    |             ^^^^^^^^^^^^^^^^^^ `fn` calls are not allowed in patterns
    |
    = help: for more information, visit https://doc.rust-lang.org/book/ch18-00-patterns.html


error[E0164]: expected tuple struct or tuple variant, found associated function `nix::Error::Sys`
   --> /home/eddie/.cargo/registry/src/github.com-1ecc6299db9ec823/shared_memory-0.11.4/src/unix.rs:119:13
    |
119 |         Err(nix::Error::Sys(e)) => return Err(ShmemError::MapCreateFailed(e as u32)),
    |             ^^^^^^^^^^^^^^^^^^ `fn` calls are not allowed in patterns
    |
    = help: for more information, visit https://doc.rust-lang.org/book/ch18-00-patterns.html


error[E0164]: expected tuple struct or tuple variant, found associated function `nix::Error::Sys`
   --> /home/eddie/.cargo/registry/src/github.com-1ecc6299db9ec823/shared_memory-0.11.4/src/unix.rs:135:13
    |
135 |         Err(nix::Error::Sys(e)) => return Err(ShmemError::MapOpenFailed(e as u32)),
    |             ^^^^^^^^^^^^^^^^^^ `fn` calls are not allowed in patterns
    |
    = help: for more information, visit https://doc.rust-lang.org/book/ch18-00-patterns.html


   error[E0164]: expected tuple struct or tuple variant, found associated function `nix::Error::Sys`
   --> /home/eddie/.cargo/registry/src/github.com-1ecc6299db9ec823/shared_memory-0.11.4/src/unix.rs:150:13
    |
150 |         Err(nix::Error::Sys(e)) => return Err(ShmemError::MapOpenFailed(e as u32)),
    |             ^^^^^^^^^^^^^^^^^^ `fn` calls are not allowed in patterns
    |
    = help: for more information, visit https://doc.rust-lang.org/book/ch18-00-patterns.html


error[E0164]: expected tuple struct or tuple variant, found associated function `nix::Error::Sys`
   --> /home/eddie/.cargo/registry/src/github.com-1ecc6299db9ec823/shared_memory-0.11.4/src/unix.rs:166:13
    |
166 |         Err(nix::Error::Sys(e)) => return Err(ShmemError::MapOpenFailed(e as u32)),
    |             ^^^^^^^^^^^^^^^^^^ `fn` calls are not allowed in patterns
    |
    = help: for more information, visit https://doc.rust-lang.org/book/ch18-00-patterns.html


 error: aborting due to 7 previous errors

 
error: could not compile `shared_memory`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --release --lib --`
```

**Comment by JEnoch** [comment]
Hi @eddie9712 ,

This issue comes from a recent change in **nix:0.22.0** that breaks the **shared-memory:0.11.4** dependency that is used by zenoh. There is already a PR in shared-memory to update it to nix:0.22.0: elast0ny/shared_memory-rs#67.

Waiting this to be sorted out in shared-memory, I temporary pushed the Cargo.lock file, allowing to stick with **nix:0.21.0** and make zenoh-python to build successfully. So just do a `git pull` and `maturin develop --release` again.

I let this issue open so we remember to remove the Cargo.lock once the issue is solved in **shared-memory**.

**Comment by eddie9712** [comment]
Hi @JEnoch, 
Thank you so much, it works, however, I got into another error when I had a go with "Your First zenoh app" in the document of Zenoh , and the error happened when I executed `zenohd --mem-storage='/myhome/**` and started to put data into `"/myhome/kitchen/temp"`:
In the terminal that I executed `zenohd --mem-storage='/myhome/**`:
```
thread 'async-std/runtime' panicked at 'called `Option::unwrap()` on a `None` value', zenoh/src/net/routing/pubsub.rs:1041:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

```

**Comment by JEnoch** [comment]
My guess is you're using `zenohd` version **0.5.0-beta.8**. Am I right ?
As we recently made some changes in the zenoh protocol, the `zenohd` 0.5.0-beta.8 is no longer compatible with the master branch of zenoh-python. You need to also build `zenohd` from the master branch of [eclipse-zenoh/zenoh](https://github.com/eclipse-zenoh/zenoh) following [those instructions](https://github.com/eclipse-zenoh/zenoh#how-to-build-it).
Sorry for the inconvenience, but zenoh is a work in progress and we plan to stabilize its protocol and APIs before a new release by September.

**Comment by eddie9712** [comment]
Yes, my `zenohd` version is 0.5.0-beta.8, I downloaded and installed it via the "apt" package manager, however, it still not work when I used the source build of the master branch :( , Here is the error I got:
```
thread 'async-std/runtime' panicked at 'range end index 2539299091331428252 out of range for slice of length 16', zenoh/src/net/protocol/core/mod.rs:192:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

```

**Comment by JEnoch** [comment]
What's the exact command you run ?
Can you set the `RUST_BACKTRACE=1` and `RUST_LOG=debug` environment variables and then re-run your command ?
Then, post the log here, please.

**Comment by eddie9712** [comment]
I ran the command:
`RUST_BACKTRACE=1 RUST_LOG=debug ./target/release/zenohd --mem-storage '/demo/example/**'`
And I got the result:
```
[2021-07-13T15:35:15Z DEBUG zenohd] zenohd v0.5.0-beta.8-192-gee629b2 built with rustc 1.55.0-nightly (955b9c0d4 2021-07-12)
[2021-07-13T15:35:15Z DEBUG zenoh_util::lib_loader] Cannot search for libraries in /home/eddie/.zenoh/lib: No such file or directory (os error 2)
[2021-07-13T15:35:15Z DEBUG zenoh::net::plugins] Plugins to load: []
[2021-07-13T15:35:15Z DEBUG zenoh_util::lib_loader] Search for libraries libzplugin_*.so to load in ["/usr/local/lib", "/usr/lib", "/home/eddie/zenoh", "/home/eddie/zenoh/target/release"]
[2021-07-13T15:35:15Z DEBUG zenoh_util::lib_loader] Do not load plugin storages from "/home/eddie/zenoh/target/release/libzplugin_storages.so" : already loaded.
[2021-07-13T15:35:15Z DEBUG zenoh_util::lib_loader] Do not load plugin rest from "/home/eddie/zenoh/target/release/libzplugin_rest.so" : already loaded.
[2021-07-13T15:35:15Z DEBUG zenoh::net::plugins] Plugin storages loaded from /usr/lib/libzplugin_storages.so
[2021-07-13T15:35:15Z DEBUG zenoh::net::plugins] Plugin rest loaded from /usr/lib/libzplugin_rest.so
[2021-07-13T15:35:15Z DEBUG zenohd] Config: add_timestamp=true;multicast_scouting=true;listener=tcp/0.0.0.0:7447;mode=router;peer
[2021-07-13T15:35:15Z INFO  zenoh::net::runtime] Using PID: 1C1807B438534B59B4DCFF0B9D60ADB4
[2021-07-13T15:35:15Z DEBUG zenoh::net::routing::network] [Peers network] Add node (self) 1C1807B438534B59B4DCFF0B9D60ADB4
[2021-07-13T15:35:15Z DEBUG zenoh::net::routing::network] [Routers network] Add node (self) 1C1807B438534B59B4DCFF0B9D60ADB4
[2021-07-13T15:35:15Z DEBUG zenoh::net::runtime::orchestrator] Listener tcp/0.0.0.0:7447 added
[2021-07-13T15:35:15Z INFO  zenoh::net::runtime::orchestrator] zenohd can be reached on tcp/192.168.1.102:7447
[2021-07-13T15:35:15Z DEBUG zenoh::net::runtime::orchestrator] UDP port bound to 224.0.0.224:7447
[2021-07-13T15:35:15Z DEBUG zenoh::net::runtime::orchestrator] Joined multicast group 224.0.0.224 on interface 192.168.1.102
[2021-07-13T15:35:15Z INFO  zenoh::net::runtime::orchestrator] zenohd listening scout messages on 224.0.0.224:7447
[2021-07-13T15:35:15Z DEBUG zenoh::net::runtime::orchestrator] UDP port bound to 192.168.1.102:48028
[2021-07-13T15:35:15Z DEBUG zenoh::net::plugins] Start plugin storages
[2021-07-13T15:35:15Z DEBUG zenoh::net::runtime::orchestrator] Waiting for UDP datagram...
[2021-07-13T15:35:15Z DEBUG zenoh::net::plugins] Start plugin rest
[2021-07-13T15:35:15Z DEBUG zenoh_util::lib_loader] Cannot search for libraries in /home/eddie/.zenoh/lib: No such file or directory (os error 2)
thread 'async-std/runtime' panicked at 'range end index 7296069191953312787 out of range for slice of length 16', zenoh/src/net/protocol/core/mod.rs:192:10
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
```

**Comment by JEnoch** [comment]
The problem is again an incompatibility between 0.5.0-beta.8 and master versions.
Your `zenohd` "master version" is loading 2 plugins in "0.5.0-beta.8" version:
 - /usr/lib/libzplugin_storages.so
 - /usr/lib/libzplugin_rest.so

Please do `apt remove zenoh zenohd zenoh-storages zenoh-rest` and try your command again (with `zenohd` "master version")

**Comment by eddie9712** [comment]
It's work ! I think I didn't remove the "apt" version completely, thanks for your helping :)
